[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.12.2"

# The following overrides are needed in order to avoid pulling in the wrong jsoniter
# version; see https://github.com/kubernetes/apimachinery/issues/46.
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[prune]
  go-tests = true
  unused-packages = true
